In [4]:
from lsg import *

import pandas as pd

In [6]:
wbcd = pd.read_csv("../../datasets/WBCD/breast_cancer_wisconsin.csv", sep=",")
wbcd = wbcd.astype("category")
wbcd = wbcd.drop(columns="Sample_code_number")

wbcd.head()

,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,2
1,5,4,4,5,7,10,3,2,1,2
2,3,1,1,1,2,2,3,1,1,2
3,6,8,8,1,3,4,3,7,1,2
4,4,1,1,3,2,1,3,1,1,2

In [14]:
res = []
for iter in range(25):

    wbcd_avatarize = avatarize(wbcd, k=20, ncp=2, drop_duplicates=False)
    wbcd_avatarize["iter"] = iter

    res.append(wbcd_avatarize)

Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction
Regarding variables types, a MCA is performed for dimension reduction

In [15]:
iteration = pd.concat(res, axis=0)
iteration.sample(10)

,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class,iter
207,5,10,10,9,6,10,10,10,5,4,16
98,10,4,10,1,5,10,4,3,1,4,1
458,4,1,1,1,2,1,1,1,1,2,13
367,7,6,6,6,4,10,7,6,6,4,4
116,5,1,1,1,2,1,1,1,1,2,14
275,10,7,6,6,4,10,7,4,1,4,9
407,3,1,2,1,2,3,3,1,1,2,20
592,1,1,1,1,2,1,1,1,1,2,12
490,3,1,3,2,3,1,1,1,1,2,0
226,5,4,3,4,7,7,3,6,1,4,12

In [16]:
iteration.to_csv("../../datasets/WBCD/wbcd_avatarized_25time_k20_nf_2.csv", index=False)